-- AUTO-GENERATED by tools/gen_rastar_api.py — do not edit by hand.
-- Covers EVERY /api/v1/client/* endpoint of the Rastar backend (see <api>/docs).
-- Update to the latest backend with ONE command:
--   python tools/gen_rastar_api.py --fetch
--
-- Every function: M.<name>(path_params..., payload, cb)
--   payload = body table (POST/PUT/PATCH) or query table (GET/DELETE); may be nil
--   cb(ok, data_or_error, raw_response)
local rastar = require "rastar.rastar"

local M = {}

local function qs(t)
    if not t then return "" end
    local parts = {}
    for k, v in pairs(t) do
        parts[#parts + 1] = tostring(k) .. "=" .. tostring(v):gsub("[^%w%-%._~]", function(c)
            return string.format("%%%02X", c:byte())
        end)
    end
    if #parts == 0 then return "" end
    return "?" .. table.concat(parts, "&")
end

-- ===== ad-positions =====
-- Get By Key
function M.get_ad_positions(key, payload, cb)
    rastar.request("/api/v1/client/ad-positions/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== ads =====
-- Get By Position Key
function M.get_ads(position_key, payload, cb)
    rastar.request("/api/v1/client/ads/" .. tostring(position_key) .. qs(payload), "GET", nil, cb)
end

-- ===== ai =====
-- List Conversations
function M.get_ai_chat_conversations(payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations" .. qs(payload), "GET", nil, cb)
end

-- Create Conversation
function M.post_ai_chat_conversations(payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations", "POST", payload, cb)
end

-- Delete Conversation
function M.delete_ai_chat_conversations(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Conversation
function M.get_ai_chat_conversations_by_conversation_id(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. qs(payload), "GET", nil, cb)
end

-- Update Conversation
function M.patch_ai_chat_conversations(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id), "PATCH", payload, cb)
end

-- Generate Conversation Title
function M.post_ai_chat_conversations_generate_title(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/generate-title", "POST", payload, cb)
end

-- Leave Conversation
function M.post_ai_chat_conversations_leave(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/leave", "POST", payload, cb)
end

-- Lookup User For Invite
function M.get_ai_chat_conversations_lookup_user(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/lookup-user" .. qs(payload), "GET", nil, cb)
end

-- List Members
function M.get_ai_chat_conversations_members(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/members" .. qs(payload), "GET", nil, cb)
end

-- Invite Member
function M.post_ai_chat_conversations_members(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/members", "POST", payload, cb)
end

-- Remove Member
function M.delete_ai_chat_conversations_members(conversation_id, member_user_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/members/" .. tostring(member_user_id) .. qs(payload), "DELETE", nil, cb)
end

-- List Messages Before
function M.get_ai_chat_conversations_messages(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/messages" .. qs(payload), "GET", nil, cb)
end

-- Send Message
function M.post_ai_chat_conversations_messages(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/messages", "POST", payload, cb)
end

-- Set Conversation Model
function M.patch_ai_chat_conversations_model(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/model", "PATCH", payload, cb)
end

-- List Participants
function M.get_ai_chat_conversations_participants(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/participants" .. qs(payload), "GET", nil, cb)
end

-- Run Function In Chat
function M.post_ai_chat_conversations_run_function(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/run-function", "POST", payload, cb)
end

-- Revoke Share
function M.delete_ai_chat_conversations_share(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/share" .. qs(payload), "DELETE", nil, cb)
end

-- Share Conversation
function M.post_ai_chat_conversations_share(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/share", "POST", payload, cb)
end

-- Signal Typing
function M.post_ai_chat_conversations_typing(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/conversations/" .. tostring(conversation_id) .. "/typing", "POST", payload, cb)
end

-- List Documents
function M.get_ai_chat_documents(payload, cb)
    rastar.request("/api/v1/client/ai/chat/documents" .. qs(payload), "GET", nil, cb)
end

-- Create Document
function M.post_ai_chat_documents(payload, cb)
    rastar.request("/api/v1/client/ai/chat/documents", "POST", payload, cb)
end

-- Delete Document
function M.delete_ai_chat_documents(document_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/documents/" .. tostring(document_id) .. qs(payload), "DELETE", nil, cb)
end

-- List Pending Invites
function M.get_ai_chat_invites(payload, cb)
    rastar.request("/api/v1/client/ai/chat/invites" .. qs(payload), "GET", nil, cb)
end

-- Accept Invite
function M.post_ai_chat_invites_accept(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/invites/" .. tostring(conversation_id) .. "/accept", "POST", payload, cb)
end

-- Decline Invite
function M.post_ai_chat_invites_decline(conversation_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/invites/" .. tostring(conversation_id) .. "/decline", "POST", payload, cb)
end

-- List Memory
function M.get_ai_chat_memory(payload, cb)
    rastar.request("/api/v1/client/ai/chat/memory" .. qs(payload), "GET", nil, cb)
end

-- Create Memory
function M.post_ai_chat_memory(payload, cb)
    rastar.request("/api/v1/client/ai/chat/memory", "POST", payload, cb)
end

-- Delete Memory
function M.delete_ai_chat_memory(memory_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/memory/" .. tostring(memory_id) .. qs(payload), "DELETE", nil, cb)
end

-- Edit User Message
function M.patch_ai_chat_messages_edit(message_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/messages/" .. tostring(message_id) .. "/edit", "PATCH", payload, cb)
end

-- React To Message
function M.post_ai_chat_messages_reaction(message_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/messages/" .. tostring(message_id) .. "/reaction", "POST", payload, cb)
end

-- Regenerate Assistant Message
function M.post_ai_chat_messages_regenerate(message_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/messages/" .. tostring(message_id) .. "/regenerate", "POST", payload, cb)
end

-- Select Message Branch
function M.post_ai_chat_messages_select(message_id, payload, cb)
    rastar.request("/api/v1/client/ai/chat/messages/" .. tostring(message_id) .. "/select", "POST", payload, cb)
end

-- Fork Shared Conversation
function M.post_ai_chat_share_fork(share_token, payload, cb)
    rastar.request("/api/v1/client/ai/chat/share/" .. tostring(share_token) .. "/fork", "POST", payload, cb)
end

-- List Function Packs
function M.get_ai_function_packs(payload, cb)
    rastar.request("/api/v1/client/ai/function-packs" .. qs(payload), "GET", nil, cb)
end

-- Get Function Pack
function M.get_ai_function_packs_by_pack_id(pack_id, payload, cb)
    rastar.request("/api/v1/client/ai/function-packs/" .. tostring(pack_id) .. qs(payload), "GET", nil, cb)
end

-- List Functions
function M.get_ai_functions(payload, cb)
    rastar.request("/api/v1/client/ai/functions" .. qs(payload), "GET", nil, cb)
end

-- Create Function
function M.post_ai_functions(payload, cb)
    rastar.request("/api/v1/client/ai/functions", "POST", payload, cb)
end

-- Browse Functions
function M.get_ai_functions_browse(payload, cb)
    rastar.request("/api/v1/client/ai/functions/browse" .. qs(payload), "GET", nil, cb)
end

-- List My Functions
function M.get_ai_functions_mine(payload, cb)
    rastar.request("/api/v1/client/ai/functions/mine" .. qs(payload), "GET", nil, cb)
end

-- Delete Function
function M.delete_ai_functions(function_id, payload, cb)
    rastar.request("/api/v1/client/ai/functions/" .. tostring(function_id) .. qs(payload), "DELETE", nil, cb)
end

-- Update Function
function M.patch_ai_functions(function_id, payload, cb)
    rastar.request("/api/v1/client/ai/functions/" .. tostring(function_id), "PATCH", payload, cb)
end

-- Get Function
function M.get_ai_functions_by_slug(slug, payload, cb)
    rastar.request("/api/v1/client/ai/functions/" .. tostring(slug) .. qs(payload), "GET", nil, cb)
end

-- Run Function
function M.post_ai_functions_run(slug, payload, cb)
    rastar.request("/api/v1/client/ai/functions/" .. tostring(slug) .. "/run", "POST", payload, cb)
end

-- List Models
function M.get_ai_models(payload, cb)
    rastar.request("/api/v1/client/ai/models" .. qs(payload), "GET", nil, cb)
end

-- Run Model
function M.post_ai_models_run(model_config_id, payload, cb)
    rastar.request("/api/v1/client/ai/models/" .. tostring(model_config_id) .. "/run", "POST", payload, cb)
end

-- ===== albums =====
-- Create Album
function M.post_albums(payload, cb)
    rastar.request("/api/v1/client/albums", "POST", payload, cb)
end

-- List My Albums
function M.get_albums_me(payload, cb)
    rastar.request("/api/v1/client/albums/me" .. qs(payload), "GET", nil, cb)
end

-- Trending Albums
function M.get_albums_trending(payload, cb)
    rastar.request("/api/v1/client/albums/trending" .. qs(payload), "GET", nil, cb)
end

-- List User Albums
function M.get_albums_users(user_id, payload, cb)
    rastar.request("/api/v1/client/albums/users/" .. tostring(user_id) .. qs(payload), "GET", nil, cb)
end

-- Delete Album
function M.delete_albums(album_id, payload, cb)
    rastar.request("/api/v1/client/albums/" .. tostring(album_id) .. qs(payload), "DELETE", nil, cb)
end

-- Update Album
function M.put_albums(album_id, payload, cb)
    rastar.request("/api/v1/client/albums/" .. tostring(album_id), "PUT", payload, cb)
end

-- Remove Content From Album
function M.delete_albums_contents(album_id, content_id, payload, cb)
    rastar.request("/api/v1/client/albums/" .. tostring(album_id) .. "/contents/" .. tostring(content_id) .. qs(payload), "DELETE", nil, cb)
end

-- Add Content To Album
function M.post_albums_contents(album_id, content_id, payload, cb)
    rastar.request("/api/v1/client/albums/" .. tostring(album_id) .. "/contents/" .. tostring(content_id), "POST", payload, cb)
end

-- ===== assets =====
-- Getuserassets
function M.get_assets(payload, cb)
    rastar.request("/api/v1/client/assets" .. qs(payload), "GET", nil, cb)
end

-- Syncuserassets
function M.post_assets_sync(payload, cb)
    rastar.request("/api/v1/client/assets/sync", "POST", payload, cb)
end

-- Removeuserassetbyrecordid
function M.delete_assets_user_asset(id, payload, cb)
    rastar.request("/api/v1/client/assets/user-asset/" .. tostring(id) .. qs(payload), "DELETE", nil, cb)
end

-- Removeuserasset
function M.delete_assets(assetId, payload, cb)
    rastar.request("/api/v1/client/assets/" .. tostring(assetId) .. qs(payload), "DELETE", nil, cb)
end

-- Getuserassetbyassetid
function M.get_assets_by_assetId(assetId, payload, cb)
    rastar.request("/api/v1/client/assets/" .. tostring(assetId) .. qs(payload), "GET", nil, cb)
end

-- Giveasset
function M.post_assets_give(assetId, payload, cb)
    rastar.request("/api/v1/client/assets/" .. tostring(assetId) .. "/give", "POST", payload, cb)
end

-- ===== auth =====
-- Basic Login
function M.post_auth_basic_login(payload, cb)
    rastar.request("/api/v1/client/auth/basic-login", "POST", payload, cb)
end

-- Basic Signup
function M.post_auth_basic_signup(payload, cb)
    rastar.request("/api/v1/client/auth/basic-signup", "POST", payload, cb)
end

-- Change Phone Email
function M.post_auth_change_phone_email(payload, cb)
    rastar.request("/api/v1/client/auth/change-phone-email", "POST", payload, cb)
end

-- Device Id Login
function M.post_auth_device_id_login(payload, cb)
    rastar.request("/api/v1/client/auth/device-id-login", "POST", payload, cb)
end

-- Logout
function M.post_auth_logout(payload, cb)
    rastar.request("/api/v1/client/auth/logout", "POST", payload, cb)
end

-- Otp Auth
function M.post_auth_otp_login(payload, cb)
    rastar.request("/api/v1/client/auth/otp-login", "POST", payload, cb)
end

-- Refresh Token
function M.post_auth_refresh_token(payload, cb)
    rastar.request("/api/v1/client/auth/refresh-token", "POST", payload, cb)
end

-- Resend Otp
function M.post_auth_resend_otp(payload, cb)
    rastar.request("/api/v1/client/auth/resend-otp", "POST", payload, cb)
end

-- Reset Password
function M.post_auth_reset_password(payload, cb)
    rastar.request("/api/v1/client/auth/reset-password", "POST", payload, cb)
end

-- Set Password
function M.post_auth_set_password(payload, cb)
    rastar.request("/api/v1/client/auth/set-password", "POST", payload, cb)
end

-- Social Login
function M.post_auth_social_login(payload, cb)
    rastar.request("/api/v1/client/auth/social-login", "POST", payload, cb)
end

-- Steam Callback
function M.get_auth_steam_callback(payload, cb)
    rastar.request("/api/v1/client/auth/steam/callback" .. qs(payload), "GET", nil, cb)
end

-- Get Steam Login Url
function M.get_auth_steam_login(payload, cb)
    rastar.request("/api/v1/client/auth/steam/login" .. qs(payload), "GET", nil, cb)
end

-- Verify Magic Link
function M.get_auth_verify_magic_link(payload, cb)
    rastar.request("/api/v1/client/auth/verify-magic-link" .. qs(payload), "GET", nil, cb)
end

-- Verify Otp
function M.post_auth_verify_otp(payload, cb)
    rastar.request("/api/v1/client/auth/verify-otp", "POST", payload, cb)
end

-- ===== avatars =====
-- List Avatars
function M.get_avatars(payload, cb)
    rastar.request("/api/v1/client/avatars" .. qs(payload), "GET", nil, cb)
end

-- List My Avatars
function M.get_avatars_mine(payload, cb)
    rastar.request("/api/v1/client/avatars/mine" .. qs(payload), "GET", nil, cb)
end

-- Get Avatar
function M.get_avatars_by_id(id, payload, cb)
    rastar.request("/api/v1/client/avatars/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Buy Avatar
function M.post_avatars_buy(id, payload, cb)
    rastar.request("/api/v1/client/avatars/" .. tostring(id) .. "/buy", "POST", payload, cb)
end

-- ===== billing =====
-- Validatesubscription
function M.post_billing_subscription_validate(payload, cb)
    rastar.request("/api/v1/client/billing/subscription/validate", "POST", payload, cb)
end

-- Validatepurchase
function M.post_billing_validate(payload, cb)
    rastar.request("/api/v1/client/billing/validate", "POST", payload, cb)
end

-- ===== blockchain =====
-- Convertdollartotoken
function M.get_blockchain_convert(network, dollar, payload, cb)
    rastar.request("/api/v1/client/blockchain/convert/" .. tostring(network) .. "/" .. tostring(dollar) .. qs(payload), "GET", nil, cb)
end

-- Getnetworks
function M.get_blockchain_networks(payload, cb)
    rastar.request("/api/v1/client/blockchain/networks" .. qs(payload), "GET", nil, cb)
end

-- Getprice
function M.get_blockchain_price(network, payload, cb)
    rastar.request("/api/v1/client/blockchain/price/" .. tostring(network) .. qs(payload), "GET", nil, cb)
end

-- Validatetransaction
function M.get_blockchain_validate(network, txHash, payload, cb)
    rastar.request("/api/v1/client/blockchain/validate/" .. tostring(network) .. "/" .. tostring(txHash) .. qs(payload), "GET", nil, cb)
end

-- ===== chance-game =====
-- List Chance Games
function M.get_chance_game_all(payload, cb)
    rastar.request("/api/v1/client/chance-game/all" .. qs(payload), "GET", nil, cb)
end

-- Get Chance Game
function M.get_chance_game(chance_game_id, payload, cb)
    rastar.request("/api/v1/client/chance-game/" .. tostring(chance_game_id) .. qs(payload), "GET", nil, cb)
end

-- Can Play
function M.get_chance_game_can_play(chance_game_id, payload, cb)
    rastar.request("/api/v1/client/chance-game/" .. tostring(chance_game_id) .. "/can-play" .. qs(payload), "GET", nil, cb)
end

-- Get Next Play Time
function M.get_chance_game_next_play_time(chance_game_id, payload, cb)
    rastar.request("/api/v1/client/chance-game/" .. tostring(chance_game_id) .. "/next-play-time" .. qs(payload), "GET", nil, cb)
end

-- Play
function M.get_chance_game_play(chance_game_id, payload, cb)
    rastar.request("/api/v1/client/chance-game/" .. tostring(chance_game_id) .. "/play" .. qs(payload), "GET", nil, cb)
end

-- Play With Ticket
function M.get_chance_game_playwithticket(chance_game_id, payload, cb)
    rastar.request("/api/v1/client/chance-game/" .. tostring(chance_game_id) .. "/playWithTicket" .. qs(payload), "GET", nil, cb)
end

-- ===== clans =====
-- List Clans
function M.get_clans(payload, cb)
    rastar.request("/api/v1/client/clans/" .. qs(payload), "GET", nil, cb)
end

-- Create Clan
function M.post_clans(payload, cb)
    rastar.request("/api/v1/client/clans/", "POST", payload, cb)
end

-- Get Clan
function M.get_clans_by_clan_id(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id) .. qs(payload), "GET", nil, cb)
end

-- Update Clan
function M.put_clans(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id), "PUT", payload, cb)
end

-- Join Clan
function M.post_clans_join(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id) .. "/join", "POST", payload, cb)
end

-- Leave Clan
function M.post_clans_leave(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id) .. "/leave", "POST", payload, cb)
end

-- Get Clan Members
function M.get_clans_members(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id) .. "/members" .. qs(payload), "GET", nil, cb)
end

-- Request To Join
function M.post_clans_request_to_join(clan_id, payload, cb)
    rastar.request("/api/v1/client/clans/" .. tostring(clan_id) .. "/request-to-join", "POST", payload, cb)
end

-- ===== content-genres =====
-- List Items
function M.get_content_genres(payload, cb)
    rastar.request("/api/v1/client/content-genres" .. qs(payload), "GET", nil, cb)
end

-- Get
function M.get_content_genres_by_id(id, payload, cb)
    rastar.request("/api/v1/client/content-genres/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== content =====
-- Delete Many Contents
function M.delete_content_bulk(payload, cb)
    rastar.request("/api/v1/client/content/bulk" .. qs(payload), "DELETE", nil, cb)
end

-- List My Contents
function M.get_content_me(payload, cb)
    rastar.request("/api/v1/client/content/me" .. qs(payload), "GET", nil, cb)
end

-- Popular Tags
function M.get_content_tags_popular(payload, cb)
    rastar.request("/api/v1/client/content/tags/popular" .. qs(payload), "GET", nil, cb)
end

-- Trending Contents
function M.get_content_trending(payload, cb)
    rastar.request("/api/v1/client/content/trending" .. qs(payload), "GET", nil, cb)
end

-- Upload Content
function M.post_content_upload(payload, cb)
    rastar.request("/api/v1/client/content/upload", "POST", payload, cb)
end

-- List User Contents
function M.get_content_users(user_id, payload, cb)
    rastar.request("/api/v1/client/content/users/" .. tostring(user_id) .. qs(payload), "GET", nil, cb)
end

-- User Tags
function M.get_content_users_tags(user_id, payload, cb)
    rastar.request("/api/v1/client/content/users/" .. tostring(user_id) .. "/tags" .. qs(payload), "GET", nil, cb)
end

-- Delete Content
function M.delete_content(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id) .. qs(payload), "DELETE", nil, cb)
end

-- Update Content
function M.put_content(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id), "PUT", payload, cb)
end

-- Stream File
function M.get_content_file(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id) .. "/file" .. qs(payload), "GET", nil, cb)
end

-- Like Content
function M.post_content_like(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id) .. "/like", "POST", payload, cb)
end

-- Signed Url
function M.get_content_signed_url(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id) .. "/signed-url" .. qs(payload), "GET", nil, cb)
end

-- View Content
function M.post_content_view(content_id, payload, cb)
    rastar.request("/api/v1/client/content/" .. tostring(content_id) .. "/view", "POST", payload, cb)
end

-- ===== contents =====
-- Get All
function M.get_contents(payload, cb)
    rastar.request("/api/v1/client/contents" .. qs(payload), "GET", nil, cb)
end

-- Create
function M.post_contents(payload, cb)
    rastar.request("/api/v1/client/contents", "POST", payload, cb)
end

-- Delete
function M.delete_contents(id, payload, cb)
    rastar.request("/api/v1/client/contents/" .. tostring(id) .. qs(payload), "DELETE", nil, cb)
end

-- Get By Id
function M.get_contents_by_id(id, payload, cb)
    rastar.request("/api/v1/client/contents/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Update
function M.patch_contents(id, payload, cb)
    rastar.request("/api/v1/client/contents/" .. tostring(id), "PATCH", payload, cb)
end

-- ===== conversations =====
-- List Conversations
function M.get_conversations(payload, cb)
    rastar.request("/api/v1/client/conversations/" .. qs(payload), "GET", nil, cb)
end

-- Create Conversation
function M.post_conversations(payload, cb)
    rastar.request("/api/v1/client/conversations/", "POST", payload, cb)
end

-- Join Group By Invite
function M.post_conversations_join(invite_code, payload, cb)
    rastar.request("/api/v1/client/conversations/join/" .. tostring(invite_code), "POST", payload, cb)
end

-- Delete Message
function M.delete_conversations_messages(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Message
function M.get_conversations_messages(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. qs(payload), "GET", nil, cb)
end

-- Edit Message
function M.put_conversations_messages(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id), "PUT", payload, cb)
end

-- Forward Message
function M.post_conversations_messages_forward(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. "/forward", "POST", payload, cb)
end

-- Remove Reaction
function M.delete_conversations_messages_reaction(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. "/reaction" .. qs(payload), "DELETE", nil, cb)
end

-- Add Reaction
function M.post_conversations_messages_reaction(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. "/reaction", "POST", payload, cb)
end

-- Reply Message
function M.post_conversations_messages_reply(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. "/reply", "POST", payload, cb)
end

-- Mark Seen
function M.post_conversations_messages_seen(message_id, payload, cb)
    rastar.request("/api/v1/client/conversations/messages/" .. tostring(message_id) .. "/seen", "POST", payload, cb)
end

-- Delete Conversation
function M.delete_conversations(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Conversation
function M.get_conversations_by_conversation_id(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. qs(payload), "GET", nil, cb)
end

-- Update Conversation
function M.put_conversations(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id), "PUT", payload, cb)
end

-- Leave Conversation
function M.post_conversations_leave(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/leave", "POST", payload, cb)
end

-- Remove Members
function M.delete_conversations_members(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members" .. qs(payload), "DELETE", nil, cb)
end

-- List Members
function M.get_conversations_members(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members" .. qs(payload), "GET", nil, cb)
end

-- Add Or Update Members
function M.post_conversations_members(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members", "POST", payload, cb)
end

-- Update My Member Metadata
function M.put_conversations_members_me(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members/me", "PUT", payload, cb)
end

-- Get Member
function M.get_conversations_members_by_conversation_id_member_user_id(conversation_id, member_user_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members/" .. tostring(member_user_id) .. qs(payload), "GET", nil, cb)
end

-- Update Member Permissions
function M.post_conversations_members_permissions(conversation_id, member_user_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/members/" .. tostring(member_user_id) .. "/permissions", "POST", payload, cb)
end

-- List Messages
function M.get_conversations_messages_by_conversation_id(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/messages" .. qs(payload), "GET", nil, cb)
end

-- Send Message
function M.post_conversations_messages(conversation_id, payload, cb)
    rastar.request("/api/v1/client/conversations/" .. tostring(conversation_id) .. "/messages", "POST", payload, cb)
end

-- ===== countries =====
-- List Countries
function M.get_countries(payload, cb)
    rastar.request("/api/v1/client/countries/" .. qs(payload), "GET", nil, cb)
end

-- Get Country
function M.get_countries_by_country_id(country_id, payload, cb)
    rastar.request("/api/v1/client/countries/" .. tostring(country_id) .. qs(payload), "GET", nil, cb)
end

-- ===== credit-packs =====
-- Consume
function M.post_credit_packs_consume(payload, cb)
    rastar.request("/api/v1/client/credit-packs/consume", "POST", payload, cb)
end

-- Getme
function M.get_credit_packs_me(payload, cb)
    rastar.request("/api/v1/client/credit-packs/me" .. qs(payload), "GET", nil, cb)
end

-- Activate
function M.post_credit_packs_activate(pack_id, payload, cb)
    rastar.request("/api/v1/client/credit-packs/" .. tostring(pack_id) .. "/activate", "POST", payload, cb)
end

-- Deactivate
function M.post_credit_packs_deactivate(pack_id, payload, cb)
    rastar.request("/api/v1/client/credit-packs/" .. tostring(pack_id) .. "/deactivate", "POST", payload, cb)
end

-- ===== credits =====
-- Getall
function M.get_credits_all(payload, cb)
    rastar.request("/api/v1/client/credits/all" .. qs(payload), "GET", nil, cb)
end

-- Use
function M.post_credits_use(payload, cb)
    rastar.request("/api/v1/client/credits/use", "POST", payload, cb)
end

-- Getbyid
function M.get_credits(creditId, payload, cb)
    rastar.request("/api/v1/client/credits/" .. tostring(creditId) .. qs(payload), "GET", nil, cb)
end

-- Gettotal
function M.get_credits_total(creditId, payload, cb)
    rastar.request("/api/v1/client/credits/" .. tostring(creditId) .. "/total" .. qs(payload), "GET", nil, cb)
end

-- ===== currencies =====
-- Add
function M.post_currencies_add(payload, cb)
    rastar.request("/api/v1/client/currencies/add", "POST", payload, cb)
end

-- Getall
function M.get_currencies_all(payload, cb)
    rastar.request("/api/v1/client/currencies/all" .. qs(payload), "GET", nil, cb)
end

-- Use
function M.post_currencies_use(payload, cb)
    rastar.request("/api/v1/client/currencies/use", "POST", payload, cb)
end

-- Getbykey
function M.get_currencies(key, payload, cb)
    rastar.request("/api/v1/client/currencies/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== dice-clash =====
-- Find All Dice Clash
function M.get_dice_clash(payload, cb)
    rastar.request("/api/v1/client/dice-clash" .. qs(payload), "GET", nil, cb)
end

-- Find One Dice Clash
function M.get_dice_clash_by_dice_clash_id(dice_clash_id, payload, cb)
    rastar.request("/api/v1/client/dice-clash/" .. tostring(dice_clash_id) .. qs(payload), "GET", nil, cb)
end

-- Play Dice Clash
function M.post_dice_clash_play(dice_clash_id, payload, cb)
    rastar.request("/api/v1/client/dice-clash/" .. tostring(dice_clash_id) .. "/play", "POST", payload, cb)
end

-- ===== dice-rocket =====
-- Find All Dice Rocket
function M.get_dice_rocket(payload, cb)
    rastar.request("/api/v1/client/dice-rocket" .. qs(payload), "GET", nil, cb)
end

-- Find One Dice Rocket
function M.get_dice_rocket_by_dice_rocket_id(dice_rocket_id, payload, cb)
    rastar.request("/api/v1/client/dice-rocket/" .. tostring(dice_rocket_id) .. qs(payload), "GET", nil, cb)
end

-- Play Dice Rocket
function M.post_dice_rocket_play(dice_rocket_id, payload, cb)
    rastar.request("/api/v1/client/dice-rocket/" .. tostring(dice_rocket_id) .. "/play", "POST", payload, cb)
end

-- ===== energies =====
-- Add
function M.post_energies_add(payload, cb)
    rastar.request("/api/v1/client/energies/add", "POST", payload, cb)
end

-- Getall
function M.get_energies_all(payload, cb)
    rastar.request("/api/v1/client/energies/all" .. qs(payload), "GET", nil, cb)
end

-- Getbyid
function M.get_energies_id(id, payload, cb)
    rastar.request("/api/v1/client/energies/id/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Getbykey
function M.get_energies_key(key, payload, cb)
    rastar.request("/api/v1/client/energies/key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Set
function M.post_energies_set(payload, cb)
    rastar.request("/api/v1/client/energies/set", "POST", payload, cb)
end

-- Use
function M.post_energies_use(payload, cb)
    rastar.request("/api/v1/client/energies/use", "POST", payload, cb)
end

-- ===== events =====
-- Send Event
function M.post_events_send(payload, cb)
    rastar.request("/api/v1/client/events/send", "POST", payload, cb)
end

-- Get Event Calculation
function M.get_events_calculate(eventType, payload, cb)
    rastar.request("/api/v1/client/events/" .. tostring(eventType) .. "/calculate" .. qs(payload), "GET", nil, cb)
end

-- Get Event Count
function M.get_events_count(eventType, payload, cb)
    rastar.request("/api/v1/client/events/" .. tostring(eventType) .. "/count" .. qs(payload), "GET", nil, cb)
end

-- Get Event History
function M.get_events_history(eventType, payload, cb)
    rastar.request("/api/v1/client/events/" .. tostring(eventType) .. "/history" .. qs(payload), "GET", nil, cb)
end

-- Get Latest Event
function M.get_events_latest(eventType, payload, cb)
    rastar.request("/api/v1/client/events/" .. tostring(eventType) .. "/latest" .. qs(payload), "GET", nil, cb)
end

-- ===== exchange =====
-- Buy Currency
function M.post_exchange_buy(payload, cb)
    rastar.request("/api/v1/client/exchange/buy", "POST", payload, cb)
end

-- Buy Currency Crypto
function M.post_exchange_crypto_buy(payload, cb)
    rastar.request("/api/v1/client/exchange/crypto/buy", "POST", payload, cb)
end

-- Exchange In App
function M.post_exchange_exchange_in_app(payload, cb)
    rastar.request("/api/v1/client/exchange/exchange-in-app", "POST", payload, cb)
end

-- Exchange In App
function M.post_exchange_in_app(payload, cb)
    rastar.request("/api/v1/client/exchange/in-app", "POST", payload, cb)
end

-- List Invoices
function M.get_exchange_invoices(payload, cb)
    rastar.request("/api/v1/client/exchange/invoices" .. qs(payload), "GET", nil, cb)
end

-- Claim Invoice By Token
function M.post_exchange_invoices_claim_by_token(payload, cb)
    rastar.request("/api/v1/client/exchange/invoices/claim-by-token", "POST", payload, cb)
end

-- Get Invoice
function M.get_exchange_invoices_by_invoice_id(invoice_id, payload, cb)
    rastar.request("/api/v1/client/exchange/invoices/" .. tostring(invoice_id) .. qs(payload), "GET", nil, cb)
end

-- Claim Invoice By Id
function M.post_exchange_invoices_claim(invoice_id, payload, cb)
    rastar.request("/api/v1/client/exchange/invoices/" .. tostring(invoice_id) .. "/claim", "POST", payload, cb)
end

-- Initiate Invoice Payment
function M.post_exchange_invoices_initiate(invoice_id, payload, cb)
    rastar.request("/api/v1/client/exchange/invoices/" .. tostring(invoice_id) .. "/initiate", "POST", payload, cb)
end

-- Sell Currency
function M.post_exchange_sell(payload, cb)
    rastar.request("/api/v1/client/exchange/sell", "POST", payload, cb)
end

-- List Transactions
function M.get_exchange_transactions(payload, cb)
    rastar.request("/api/v1/client/exchange/transactions" .. qs(payload), "GET", nil, cb)
end

-- Get Transaction
function M.get_exchange_transactions_by_transaction_id(transaction_id, payload, cb)
    rastar.request("/api/v1/client/exchange/transactions/" .. tostring(transaction_id) .. qs(payload), "GET", nil, cb)
end

-- ===== faqs =====
-- Get Faqs
function M.get_faqs(payload, cb)
    rastar.request("/api/v1/client/faqs" .. qs(payload), "GET", nil, cb)
end

-- Find One
function M.get_faqs_by_id(id, payload, cb)
    rastar.request("/api/v1/client/faqs/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== friends =====
-- Acceptfriendrequest
function M.post_friends_accept(payload, cb)
    rastar.request("/api/v1/client/friends/accept", "POST", payload, cb)
end

-- Cancelfriendrequest
function M.post_friends_cancel(payload, cb)
    rastar.request("/api/v1/client/friends/cancel", "POST", payload, cb)
end

-- Getfriendslist
function M.get_friends_list(payload, cb)
    rastar.request("/api/v1/client/friends/list" .. qs(payload), "GET", nil, cb)
end

-- Findmutualfriends
function M.get_friends_mutual(otherUserId, payload, cb)
    rastar.request("/api/v1/client/friends/mutual/" .. tostring(otherUserId) .. qs(payload), "GET", nil, cb)
end

-- Rejectfriendrequest
function M.post_friends_reject(payload, cb)
    rastar.request("/api/v1/client/friends/reject", "POST", payload, cb)
end

-- Removefriend
function M.delete_friends_remove(payload, cb)
    rastar.request("/api/v1/client/friends/remove" .. qs(payload), "DELETE", nil, cb)
end

-- Requestfriend
function M.post_friends_request(payload, cb)
    rastar.request("/api/v1/client/friends/request", "POST", payload, cb)
end

-- Getreceivedfriendrequests
function M.get_friends_requests_received(payload, cb)
    rastar.request("/api/v1/client/friends/requests/received" .. qs(payload), "GET", nil, cb)
end

-- Getsentfriendrequests
function M.get_friends_requests_sent(payload, cb)
    rastar.request("/api/v1/client/friends/requests/sent" .. qs(payload), "GET", nil, cb)
end

-- Suggestfriends
function M.get_friends_suggestions(payload, cb)
    rastar.request("/api/v1/client/friends/suggestions" .. qs(payload), "GET", nil, cb)
end

-- ===== games =====
-- Findallgames
function M.get_games(payload, cb)
    rastar.request("/api/v1/client/games" .. qs(payload), "GET", nil, cb)
end

-- Findusergamebygameid
function M.get_games_my_games_games(gameId, payload, cb)
    rastar.request("/api/v1/client/games/my-games/games/" .. tostring(gameId) .. qs(payload), "GET", nil, cb)
end

-- Findusergames
function M.get_games_my_games_list(payload, cb)
    rastar.request("/api/v1/client/games/my-games/list" .. qs(payload), "GET", nil, cb)
end

-- Findoneusergame
function M.get_games_my_games(userGameId, payload, cb)
    rastar.request("/api/v1/client/games/my-games/" .. tostring(userGameId) .. qs(payload), "GET", nil, cb)
end

-- Giveusergame
function M.post_games_give(gameId, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(gameId) .. "/give", "POST", payload, cb)
end

-- Play
function M.post_games_play(gameId, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(gameId) .. "/play", "POST", payload, cb)
end

-- Sendresult
function M.post_games_send_result(gameId, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(gameId) .. "/send-result", "POST", payload, cb)
end

-- Sendscore
function M.post_games_send_score(gameId, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(gameId) .. "/send-score", "POST", payload, cb)
end

-- Updatemetadata
function M.patch_games_update_metadata(gameId, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(gameId) .. "/update-metadata", "PATCH", payload, cb)
end

-- Findone
function M.get_games_by_id(id, payload, cb)
    rastar.request("/api/v1/client/games/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== gifts =====
-- List My Gift Codes
function M.get_gifts(payload, cb)
    rastar.request("/api/v1/client/gifts" .. qs(payload), "GET", nil, cb)
end

-- Redeem Gift
function M.post_gifts_redeem(payload, cb)
    rastar.request("/api/v1/client/gifts/redeem", "POST", payload, cb)
end

-- ===== global-variables =====
-- Get All
function M.get_global_variables_all(payload, cb)
    rastar.request("/api/v1/client/global-variables/all" .. qs(payload), "GET", nil, cb)
end

-- Get By Key
function M.get_global_variables(key, payload, cb)
    rastar.request("/api/v1/client/global-variables/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== languages =====
-- Get All
function M.get_languages(payload, cb)
    rastar.request("/api/v1/client/languages" .. qs(payload), "GET", nil, cb)
end

-- Get By Id
function M.get_languages_by_id(id, payload, cb)
    rastar.request("/api/v1/client/languages/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== leaderboards =====
-- List Leaderboards
function M.get_leaderboards(payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. qs(payload), "GET", nil, cb)
end

-- List Active Leaderboards
function M.get_leaderboards_active(payload, cb)
    rastar.request("/api/v1/client/leaderboards/active" .. qs(payload), "GET", nil, cb)
end

-- Get Leaderboard By Key
function M.get_leaderboards_key(key, payload, cb)
    rastar.request("/api/v1/client/leaderboards/key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Get Leaderboard
function M.get_leaderboards_by_leaderboard_id(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. qs(payload), "GET", nil, cb)
end

-- Get Leaderboard History By Version
function M.get_leaderboards_history(leaderboard_id, version, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/history/" .. tostring(version) .. qs(payload), "GET", nil, cb)
end

-- Get Neighbours
function M.get_leaderboards_neighbours(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/neighbours" .. qs(payload), "GET", nil, cb)
end

-- Get Rank Users Leaderboard
function M.get_leaderboards_ranks(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/ranks" .. qs(payload), "GET", nil, cb)
end

-- Register Score
function M.post_leaderboards_register_score(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/register-score", "POST", payload, cb)
end

-- Get Tier Leaderboard
function M.get_leaderboards_tiers_scores(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/tiers/scores" .. qs(payload), "GET", nil, cb)
end

-- Get Self Neighbours
function M.get_leaderboards_users_neighbors(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/users/neighbors" .. qs(payload), "GET", nil, cb)
end

-- Get User Rank
function M.get_leaderboards_users_rank(leaderboard_id, payload, cb)
    rastar.request("/api/v1/client/leaderboards/" .. tostring(leaderboard_id) .. "/users/rank" .. qs(payload), "GET", nil, cb)
end

-- ===== lotto-dice =====
-- Get all Lotto Dice (paginated, filterable)
function M.get_lotto_dice(payload, cb)
    rastar.request("/api/v1/client/lotto-dice" .. qs(payload), "GET", nil, cb)
end

-- Buy a ticket for a lotto-dice game. One ticket per (user, game); the ticket's code is rolled with a CSPRNG.
function M.post_lotto_dice_buy_ticket(payload, cb)
    rastar.request("/api/v1/client/lotto-dice/buy-ticket", "POST", payload, cb)
end

-- Get Lotto Dice by ID
function M.get_lotto_dice_by_lotto_dice_id(lotto_dice_id, payload, cb)
    rastar.request("/api/v1/client/lotto-dice/" .. tostring(lotto_dice_id) .. qs(payload), "GET", nil, cb)
end

-- ===== lucky-dice =====
-- Find All Lucky Dice
function M.get_lucky_dice(payload, cb)
    rastar.request("/api/v1/client/lucky-dice" .. qs(payload), "GET", nil, cb)
end

-- Find One Lucky Dice
function M.get_lucky_dice_by_lucky_dice_id(lucky_dice_id, payload, cb)
    rastar.request("/api/v1/client/lucky-dice/" .. tostring(lucky_dice_id) .. qs(payload), "GET", nil, cb)
end

-- List Lucky Dice History
function M.get_lucky_dice_history(lucky_dice_id, payload, cb)
    rastar.request("/api/v1/client/lucky-dice/" .. tostring(lucky_dice_id) .. "/history" .. qs(payload), "GET", nil, cb)
end

-- Get My Lucky Dice State
function M.get_lucky_dice_me(lucky_dice_id, payload, cb)
    rastar.request("/api/v1/client/lucky-dice/" .. tostring(lucky_dice_id) .. "/me" .. qs(payload), "GET", nil, cb)
end

-- Play Lucky Dice
function M.post_lucky_dice_play(lucky_dice_id, payload, cb)
    rastar.request("/api/v1/client/lucky-dice/" .. tostring(lucky_dice_id) .. "/play", "POST", payload, cb)
end

-- ===== meta-relations =====
-- Getall
function M.get_meta_relations_all(payload, cb)
    rastar.request("/api/v1/client/meta-relations/all" .. qs(payload), "GET", nil, cb)
end

-- ===== metas =====
-- Add
function M.post_metas_add(payload, cb)
    rastar.request("/api/v1/client/metas/add", "POST", payload, cb)
end

-- Getall
function M.get_metas_all(payload, cb)
    rastar.request("/api/v1/client/metas/all" .. qs(payload), "GET", nil, cb)
end

-- Set
function M.post_metas_set(payload, cb)
    rastar.request("/api/v1/client/metas/set", "POST", payload, cb)
end

-- Getbykey
function M.get_metas(key, payload, cb)
    rastar.request("/api/v1/client/metas/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== multiplayer-rooms =====
-- List Rooms
function M.get_multiplayer_rooms(payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms" .. qs(payload), "GET", nil, cb)
end

-- Create Room
function M.post_multiplayer_rooms(payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms", "POST", payload, cb)
end

-- Join By Invite
function M.post_multiplayer_rooms_by_invite_join(invite_link, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/by-invite/" .. tostring(invite_link) .. "/join", "POST", payload, cb)
end

-- Get Room
function M.get_multiplayer_rooms_by_room_id(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. qs(payload), "GET", nil, cb)
end

-- Cancel Room
function M.post_multiplayer_rooms_cancel(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/cancel", "POST", payload, cb)
end

-- Join Room
function M.post_multiplayer_rooms_join(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/join", "POST", payload, cb)
end

-- Leave Room
function M.post_multiplayer_rooms_leave(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/leave", "POST", payload, cb)
end

-- Ready In Room
function M.post_multiplayer_rooms_ready(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/ready", "POST", payload, cb)
end

-- Submit Scores
function M.post_multiplayer_rooms_scores(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/scores", "POST", payload, cb)
end

-- Start Room
function M.post_multiplayer_rooms_start(room_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer-rooms/" .. tostring(room_id) .. "/start", "POST", payload, cb)
end

-- ===== multiplayer =====
-- List Multiplayer Games
function M.get_multiplayer_games(payload, cb)
    rastar.request("/api/v1/client/multiplayer/games" .. qs(payload), "GET", nil, cb)
end

-- Get Multiplayer Game By Key
function M.get_multiplayer_games_by_key(key, payload, cb)
    rastar.request("/api/v1/client/multiplayer/games/by-key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Get Multiplayer Game
function M.get_multiplayer_games_by_game_id(game_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer/games/" .. tostring(game_id) .. qs(payload), "GET", nil, cb)
end

-- Get Multiplayer Histories
function M.get_multiplayer_histories(payload, cb)
    rastar.request("/api/v1/client/multiplayer/histories" .. qs(payload), "GET", nil, cb)
end

-- Get Multiplayer History
function M.get_multiplayer_histories_by_history_id(history_id, payload, cb)
    rastar.request("/api/v1/client/multiplayer/histories/" .. tostring(history_id) .. qs(payload), "GET", nil, cb)
end

-- ===== mystery-dice =====
-- Answer Mystery Dice
function M.post_mystery_dice_answer(game_id, payload, cb)
    rastar.request("/api/v1/client/mystery-dice/" .. tostring(game_id) .. "/answer", "POST", payload, cb)
end

-- Play Mystery Dice
function M.get_mystery_dice_play(mystery_dice_id, payload, cb)
    rastar.request("/api/v1/client/mystery-dice/" .. tostring(mystery_dice_id) .. "/play" .. qs(payload), "GET", nil, cb)
end

-- ===== payments =====
-- Findall
function M.get_payments(payload, cb)
    rastar.request("/api/v1/client/payments" .. qs(payload), "GET", nil, cb)
end

-- Initiatebilling
function M.post_payments_billing_initiate(payload, cb)
    rastar.request("/api/v1/client/payments/billing/initiate", "POST", payload, cb)
end

-- Initiateblockchainpayment
function M.post_payments_blockchain_initiate(payload, cb)
    rastar.request("/api/v1/client/payments/blockchain/initiate", "POST", payload, cb)
end

-- Paymentcallback
function M.get_payments_callback(payload, cb)
    rastar.request("/api/v1/client/payments/callback" .. qs(payload), "GET", nil, cb)
end

-- Initiatepayment
function M.post_payments_initiate(payload, cb)
    rastar.request("/api/v1/client/payments/initiate", "POST", payload, cb)
end

-- Previewpayment
function M.post_payments_preview(payload, cb)
    rastar.request("/api/v1/client/payments/preview", "POST", payload, cb)
end

-- Stripewebhook
function M.post_payments_stripe_webhook(payload, cb)
    rastar.request("/api/v1/client/payments/stripe/webhook", "POST", payload, cb)
end

-- Getpayment
function M.get_payments_by_id(id, payload, cb)
    rastar.request("/api/v1/client/payments/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Submitbilling
function M.post_payments_billing_submit(id, payload, cb)
    rastar.request("/api/v1/client/payments/" .. tostring(id) .. "/billing/submit", "POST", payload, cb)
end

-- Submitblockchaintransaction
function M.post_payments_blockchain_submit(id, payload, cb)
    rastar.request("/api/v1/client/payments/" .. tostring(id) .. "/blockchain/submit", "POST", payload, cb)
end

-- ===== persons =====
-- List Items
function M.get_persons(payload, cb)
    rastar.request("/api/v1/client/persons" .. qs(payload), "GET", nil, cb)
end

-- Get
function M.get_persons_by_id(id, payload, cb)
    rastar.request("/api/v1/client/persons/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== prediction =====
-- Findall
function M.get_prediction_events(payload, cb)
    rastar.request("/api/v1/client/prediction/events" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_events_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/events/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_options(payload, cb)
    rastar.request("/api/v1/client/prediction/options" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_options_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/options/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_question_event_results(payload, cb)
    rastar.request("/api/v1/client/prediction/question-event-results" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_question_event_results_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/question-event-results/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_question_events(payload, cb)
    rastar.request("/api/v1/client/prediction/question-events" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_question_events_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/question-events/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_question_packs(payload, cb)
    rastar.request("/api/v1/client/prediction/question-packs" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_question_packs_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/question-packs/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_questions(payload, cb)
    rastar.request("/api/v1/client/prediction/questions" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_prediction_questions_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/questions/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Findall
function M.get_prediction_user_question_events(payload, cb)
    rastar.request("/api/v1/client/prediction/user-question-events" .. qs(payload), "GET", nil, cb)
end

-- Create
function M.post_prediction_user_question_events(payload, cb)
    rastar.request("/api/v1/client/prediction/user-question-events", "POST", payload, cb)
end

-- Findone
function M.get_prediction_user_question_events_by_id(id, payload, cb)
    rastar.request("/api/v1/client/prediction/user-question-events/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Update
function M.patch_prediction_user_question_events(id, payload, cb)
    rastar.request("/api/v1/client/prediction/user-question-events/" .. tostring(id), "PATCH", payload, cb)
end

-- Findmystatistic
function M.get_prediction_user_statistics_me(payload, cb)
    rastar.request("/api/v1/client/prediction/user-statistics/me" .. qs(payload), "GET", nil, cb)
end

-- ===== preset-message-packs =====
-- Getall
function M.get_preset_message_packs_all(payload, cb)
    rastar.request("/api/v1/client/preset-message-packs/all" .. qs(payload), "GET", nil, cb)
end

-- Getbyid
function M.get_preset_message_packs(presetMessagePackId, payload, cb)
    rastar.request("/api/v1/client/preset-message-packs/" .. tostring(presetMessagePackId) .. qs(payload), "GET", nil, cb)
end

-- ===== preset-messages =====
-- Getbycode
function M.get_preset_messages_code(code, payload, cb)
    rastar.request("/api/v1/client/preset-messages/code/" .. tostring(code) .. qs(payload), "GET", nil, cb)
end

-- Getbyid
function M.get_preset_messages_id(id, payload, cb)
    rastar.request("/api/v1/client/preset-messages/id/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Getbypack
function M.get_preset_messages_pack(presetMessagePackId, payload, cb)
    rastar.request("/api/v1/client/preset-messages/pack/" .. tostring(presetMessagePackId) .. qs(payload), "GET", nil, cb)
end

-- ===== prizes =====
-- Getuserprizes
function M.get_prizes(payload, cb)
    rastar.request("/api/v1/client/prizes" .. qs(payload), "GET", nil, cb)
end

-- Claimprize
function M.post_prizes_claim(id, payload, cb)
    rastar.request("/api/v1/client/prizes/" .. tostring(id) .. "/claim", "POST", payload, cb)
end

-- Getuserprizebyid
function M.get_prizes_by_prizeId(prizeId, payload, cb)
    rastar.request("/api/v1/client/prizes/" .. tostring(prizeId) .. qs(payload), "GET", nil, cb)
end

-- Sendgift
function M.post_prizes_send_gift(prizeId, payload, cb)
    rastar.request("/api/v1/client/prizes/" .. tostring(prizeId) .. "/send-gift", "POST", payload, cb)
end

-- ===== projects =====
-- List Projects
function M.get_projects(payload, cb)
    rastar.request("/api/v1/client/projects" .. qs(payload), "GET", nil, cb)
end

-- Create Project
function M.post_projects(payload, cb)
    rastar.request("/api/v1/client/projects", "POST", payload, cb)
end

-- Delete Project
function M.delete_projects(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Project
function M.get_projects_by_project_id(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. qs(payload), "GET", nil, cb)
end

-- Update Project
function M.patch_projects(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id), "PATCH", payload, cb)
end

-- Lookup Project User
function M.get_projects_lookup_user(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. "/lookup-user" .. qs(payload), "GET", nil, cb)
end

-- List Project Members
function M.get_projects_members(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. "/members" .. qs(payload), "GET", nil, cb)
end

-- Add Project Member
function M.post_projects_members(project_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. "/members", "POST", payload, cb)
end

-- Remove Project Member
function M.delete_projects_members(project_id, user_id, payload, cb)
    rastar.request("/api/v1/client/projects/" .. tostring(project_id) .. "/members/" .. tostring(user_id) .. qs(payload), "DELETE", nil, cb)
end

-- ===== public-api-keys =====
-- List Public Api Keys
function M.get_public_api_keys(payload, cb)
    rastar.request("/api/v1/client/public-api-keys" .. qs(payload), "GET", nil, cb)
end

-- Create Public Api Key
function M.post_public_api_keys(payload, cb)
    rastar.request("/api/v1/client/public-api-keys", "POST", payload, cb)
end

-- Delete Public Api Key
function M.delete_public_api_keys(key_id, payload, cb)
    rastar.request("/api/v1/client/public-api-keys/" .. tostring(key_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Public Api Key
function M.get_public_api_keys_by_key_id(key_id, payload, cb)
    rastar.request("/api/v1/client/public-api-keys/" .. tostring(key_id) .. qs(payload), "GET", nil, cb)
end

-- Update Public Api Key
function M.patch_public_api_keys(key_id, payload, cb)
    rastar.request("/api/v1/client/public-api-keys/" .. tostring(key_id), "PATCH", payload, cb)
end

-- ===== publishing =====
-- Getall
function M.get_publishing_news(payload, cb)
    rastar.request("/api/v1/client/publishing/news" .. qs(payload), "GET", nil, cb)
end

-- Getallcomments
function M.get_publishing_news_comments(payload, cb)
    rastar.request("/api/v1/client/publishing/news/comments" .. qs(payload), "GET", nil, cb)
end

-- Create
function M.post_publishing_news_comments(payload, cb)
    rastar.request("/api/v1/client/publishing/news/comments", "POST", payload, cb)
end

-- Changeacceptstate
function M.patch_publishing_news_comments_accept_state(id, payload, cb)
    rastar.request("/api/v1/client/publishing/news/comments/" .. tostring(id) .. "/accept-state", "PATCH", payload, cb)
end

-- Seen
function M.post_publishing_news_seen(id, payload, cb)
    rastar.request("/api/v1/client/publishing/news/" .. tostring(id) .. "/seen", "POST", payload, cb)
end

-- ===== quiz-v2 =====
-- Get Hint
function M.get_quiz_v2_hints(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/hints/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Buy Hint
function M.post_quiz_v2_hints_buy(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/hints/" .. tostring(id) .. "/buy", "POST", payload, cb)
end

-- Buy Hint
function M.post_quiz_v2_hints_use(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/hints/" .. tostring(id) .. "/use", "POST", payload, cb)
end

-- List Packs
function M.get_quiz_v2_packs(payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs" .. qs(payload), "GET", nil, cb)
end

-- Open Packs
function M.get_quiz_v2_packs_open(payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/open" .. qs(payload), "GET", nil, cb)
end

-- Random Pack
function M.get_quiz_v2_packs_random(payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/random" .. qs(payload), "GET", nil, cb)
end

-- Statistics
function M.get_quiz_v2_packs_statistics(payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/statistics" .. qs(payload), "GET", nil, cb)
end

-- Get Pack
function M.get_quiz_v2_packs_by_id(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Answer Pack
function M.post_quiz_v2_packs_answer(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. "/answer", "POST", payload, cb)
end

-- Answer All Pack
function M.post_quiz_v2_packs_answer_all(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. "/answer-all", "POST", payload, cb)
end

-- Close Pack
function M.post_quiz_v2_packs_close(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. "/close", "POST", payload, cb)
end

-- Open By Id
function M.get_quiz_v2_packs_open_by_id(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. "/open" .. qs(payload), "GET", nil, cb)
end

-- Play Pack
function M.post_quiz_v2_packs_play(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/packs/" .. tostring(id) .. "/play", "POST", payload, cb)
end

-- List Quizzes For User
function M.get_quiz_v2_quizzes(payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes" .. qs(payload), "GET", nil, cb)
end

-- Get Quiz
function M.get_quiz_v2_quizzes_by_id(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Answer Quiz
function M.post_quiz_v2_quizzes_answer(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/answer", "POST", payload, cb)
end

-- Get Quiz Reaction Summary
function M.get_quiz_v2_quizzes_reaction(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/reaction" .. qs(payload), "GET", nil, cb)
end

-- Send Quiz Reaction
function M.post_quiz_v2_quizzes_reaction(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/reaction", "POST", payload, cb)
end

-- Send Quiz Report
function M.post_quiz_v2_quizzes_report(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/report", "POST", payload, cb)
end

-- Get Quiz Reports
function M.get_quiz_v2_quizzes_reports(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/reports" .. qs(payload), "GET", nil, cb)
end

-- Start Quiz
function M.get_quiz_v2_quizzes_start(id, payload, cb)
    rastar.request("/api/v1/client/quiz-v2/quizzes/" .. tostring(id) .. "/start" .. qs(payload), "GET", nil, cb)
end

-- ===== read-only-variables =====
-- Getall
function M.get_read_only_variables_all(payload, cb)
    rastar.request("/api/v1/client/read-only-variables/all" .. qs(payload), "GET", nil, cb)
end

-- Give
function M.post_read_only_variables_give(payload, cb)
    rastar.request("/api/v1/client/read-only-variables/give", "POST", payload, cb)
end

-- Getbyid
function M.get_read_only_variables_id(id, payload, cb)
    rastar.request("/api/v1/client/read-only-variables/id/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Getbykey
function M.get_read_only_variables(key, payload, cb)
    rastar.request("/api/v1/client/read-only-variables/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== realtime =====
-- Create Realtime Room
function M.post_realtime_rooms(payload, cb)
    rastar.request("/api/v1/client/realtime/rooms", "POST", payload, cb)
end

-- Mint Realtime Token
function M.post_realtime_token(payload, cb)
    rastar.request("/api/v1/client/realtime/token", "POST", payload, cb)
end

-- ===== reports =====
-- Reportuser
function M.post_reports(payload, cb)
    rastar.request("/api/v1/client/reports", "POST", payload, cb)
end

-- Getreports
function M.get_reports_list(payload, cb)
    rastar.request("/api/v1/client/reports/list" .. qs(payload), "GET", nil, cb)
end

-- Gettitles
function M.get_reports_titles(payload, cb)
    rastar.request("/api/v1/client/reports/titles" .. qs(payload), "GET", nil, cb)
end

-- Gettitlebytitle
function M.get_reports_titles_by_title(payload, cb)
    rastar.request("/api/v1/client/reports/titles/by-title" .. qs(payload), "GET", nil, cb)
end

-- Gettitlebyid
function M.get_reports_titles_by_id(id, payload, cb)
    rastar.request("/api/v1/client/reports/titles/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Getreportbyid
function M.get_reports(id, payload, cb)
    rastar.request("/api/v1/client/reports/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== reusable-workflow-nodes =====
-- List Catalog
function M.get_reusable_workflow_nodes(payload, cb)
    rastar.request("/api/v1/client/reusable-workflow-nodes" .. qs(payload), "GET", nil, cb)
end

-- Update Reusable Node
function M.patch_reusable_workflow_nodes(reusable_id, payload, cb)
    rastar.request("/api/v1/client/reusable-workflow-nodes/" .. tostring(reusable_id), "PATCH", payload, cb)
end

-- ===== sealed-variables =====
-- Getall
function M.get_sealed_variables_all(payload, cb)
    rastar.request("/api/v1/client/sealed-variables/all" .. qs(payload), "GET", nil, cb)
end

-- Getbykey
function M.get_sealed_variables_key(key, payload, cb)
    rastar.request("/api/v1/client/sealed-variables/key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Getbyid
function M.get_sealed_variables(id, payload, cb)
    rastar.request("/api/v1/client/sealed-variables/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== shops =====
-- Findall
function M.get_shops(payload, cb)
    rastar.request("/api/v1/client/shops" .. qs(payload), "GET", nil, cb)
end

-- Findone
function M.get_shops_by_id(id, payload, cb)
    rastar.request("/api/v1/client/shops/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== snake =====
-- Find All Snake
function M.get_snake(payload, cb)
    rastar.request("/api/v1/client/snake" .. qs(payload), "GET", nil, cb)
end

-- Find One Snake
function M.get_snake_by_snake_id(snake_id, payload, cb)
    rastar.request("/api/v1/client/snake/" .. tostring(snake_id) .. qs(payload), "GET", nil, cb)
end

-- Find User Snake
function M.get_snake_me(snake_id, payload, cb)
    rastar.request("/api/v1/client/snake/" .. tostring(snake_id) .. "/me" .. qs(payload), "GET", nil, cb)
end

-- Submit Snake Score
function M.post_snake_score(snake_id, payload, cb)
    rastar.request("/api/v1/client/snake/" .. tostring(snake_id) .. "/score", "POST", payload, cb)
end

-- Start Snake
function M.post_snake_start(snake_id, payload, cb)
    rastar.request("/api/v1/client/snake/" .. tostring(snake_id) .. "/start", "POST", payload, cb)
end

-- ===== sponsors =====
-- Get Sponsors
function M.get_sponsors(payload, cb)
    rastar.request("/api/v1/client/sponsors" .. qs(payload), "GET", nil, cb)
end

-- Get By Key
function M.get_sponsors_by_key(key, payload, cb)
    rastar.request("/api/v1/client/sponsors/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- ===== streaks =====
-- List My Streaks
function M.get_streaks(payload, cb)
    rastar.request("/api/v1/client/streaks" .. qs(payload), "GET", nil, cb)
end

-- Get My Streak By Key
function M.get_streaks_by_key(key, payload, cb)
    rastar.request("/api/v1/client/streaks/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Trigger My Streak
function M.post_streaks_trigger(key, payload, cb)
    rastar.request("/api/v1/client/streaks/" .. tostring(key) .. "/trigger", "POST", payload, cb)
end

-- Use My Streak Freeze
function M.post_streaks_use_freeze(key, payload, cb)
    rastar.request("/api/v1/client/streaks/" .. tostring(key) .. "/use-freeze", "POST", payload, cb)
end

-- ===== subscription-plans =====
-- Getallplans
function M.get_subscription_plans_all(payload, cb)
    rastar.request("/api/v1/client/subscription-plans/all" .. qs(payload), "GET", nil, cb)
end

-- Getplanbyid
function M.get_subscription_plans(id, payload, cb)
    rastar.request("/api/v1/client/subscription-plans/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== subscriptions =====
-- Getall
function M.get_subscriptions_all(payload, cb)
    rastar.request("/api/v1/client/subscriptions/all" .. qs(payload), "GET", nil, cb)
end

-- Give
function M.post_subscriptions_give(payload, cb)
    rastar.request("/api/v1/client/subscriptions/give", "POST", payload, cb)
end

-- ===== tasks =====
-- Findusertasks
function M.get_tasks(payload, cb)
    rastar.request("/api/v1/client/tasks" .. qs(payload), "GET", nil, cb)
end

-- Syncusertasks
function M.post_tasks_sync(payload, cb)
    rastar.request("/api/v1/client/tasks/sync", "POST", payload, cb)
end

-- Findone
function M.get_tasks_by_taskId(taskId, payload, cb)
    rastar.request("/api/v1/client/tasks/" .. tostring(taskId) .. qs(payload), "GET", nil, cb)
end

-- Claimprize
function M.post_tasks_claim_prize(taskId, payload, cb)
    rastar.request("/api/v1/client/tasks/" .. tostring(taskId) .. "/claim-prize", "POST", payload, cb)
end

-- ===== user-block =====
-- Blockuser
function M.post_user_block_block(payload, cb)
    rastar.request("/api/v1/client/user-block/block", "POST", payload, cb)
end

-- Getblockedusers
function M.get_user_block_list(payload, cb)
    rastar.request("/api/v1/client/user-block/list" .. qs(payload), "GET", nil, cb)
end

-- Unblockuser
function M.delete_user_block_unblock(payload, cb)
    rastar.request("/api/v1/client/user-block/unblock" .. qs(payload), "DELETE", nil, cb)
end

-- ===== user-contents =====
-- Get All User Contents
function M.get_user_contents(payload, cb)
    rastar.request("/api/v1/client/user-contents" .. qs(payload), "GET", nil, cb)
end

-- Create User Content
function M.post_user_contents(payload, cb)
    rastar.request("/api/v1/client/user-contents", "POST", payload, cb)
end

-- Delete User Content
function M.delete_user_contents(id, payload, cb)
    rastar.request("/api/v1/client/user-contents/" .. tostring(id) .. qs(payload), "DELETE", nil, cb)
end

-- Get User Content By Id
function M.get_user_contents_by_id(id, payload, cb)
    rastar.request("/api/v1/client/user-contents/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Update User Content
function M.patch_user_contents(id, payload, cb)
    rastar.request("/api/v1/client/user-contents/" .. tostring(id), "PATCH", payload, cb)
end

-- ===== user-data =====
-- Get All
function M.get_user_data(payload, cb)
    rastar.request("/api/v1/client/user-data" .. qs(payload), "GET", nil, cb)
end

-- Create
function M.post_user_data(payload, cb)
    rastar.request("/api/v1/client/user-data", "POST", payload, cb)
end

-- Get By Key
function M.get_user_data_key(key, payload, cb)
    rastar.request("/api/v1/client/user-data/key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Delete
function M.delete_user_data(id, payload, cb)
    rastar.request("/api/v1/client/user-data/" .. tostring(id) .. qs(payload), "DELETE", nil, cb)
end

-- Get By Id
function M.get_user_data_by_id(id, payload, cb)
    rastar.request("/api/v1/client/user-data/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== user-preset-message-packs =====
-- Getall
function M.get_user_preset_message_packs_all(payload, cb)
    rastar.request("/api/v1/client/user-preset-message-packs/all" .. qs(payload), "GET", nil, cb)
end

-- Getbyid
function M.get_user_preset_message_packs(presetMessagePackId, payload, cb)
    rastar.request("/api/v1/client/user-preset-message-packs/" .. tostring(presetMessagePackId) .. qs(payload), "GET", nil, cb)
end

-- Add
function M.post_user_preset_message_packs_add(presetMessagePackId, payload, cb)
    rastar.request("/api/v1/client/user-preset-message-packs/" .. tostring(presetMessagePackId) .. "/add", "POST", payload, cb)
end

-- Give
function M.post_user_preset_message_packs_give(presetMessagePackId, payload, cb)
    rastar.request("/api/v1/client/user-preset-message-packs/" .. tostring(presetMessagePackId) .. "/give", "POST", payload, cb)
end

-- ===== user-quizzes =====
-- List My User Quizzes
function M.get_user_quizzes(payload, cb)
    rastar.request("/api/v1/client/user-quizzes" .. qs(payload), "GET", nil, cb)
end

-- Create User Quiz
function M.post_user_quizzes(payload, cb)
    rastar.request("/api/v1/client/user-quizzes", "POST", payload, cb)
end

-- Delete My User Quiz
function M.delete_user_quizzes(quiz_id, payload, cb)
    rastar.request("/api/v1/client/user-quizzes/" .. tostring(quiz_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get My User Quiz
function M.get_user_quizzes_by_quiz_id(quiz_id, payload, cb)
    rastar.request("/api/v1/client/user-quizzes/" .. tostring(quiz_id) .. qs(payload), "GET", nil, cb)
end

-- Update My User Quiz
function M.patch_user_quizzes(quiz_id, payload, cb)
    rastar.request("/api/v1/client/user-quizzes/" .. tostring(quiz_id), "PATCH", payload, cb)
end

-- ===== users =====
-- Get By Invite Code
function M.get_users_invite_code(inviteCode, payload, cb)
    rastar.request("/api/v1/client/users/invite-code/" .. tostring(inviteCode) .. qs(payload), "GET", nil, cb)
end

-- Delete Account
function M.delete_users_me(payload, cb)
    rastar.request("/api/v1/client/users/me" .. qs(payload), "DELETE", nil, cb)
end

-- Me
function M.get_users_me(payload, cb)
    rastar.request("/api/v1/client/users/me" .. qs(payload), "GET", nil, cb)
end

-- Search
function M.get_users_search(payload, cb)
    rastar.request("/api/v1/client/users/search" .. qs(payload), "GET", nil, cb)
end

-- Set Inviter
function M.post_users_set_inviter(payload, cb)
    rastar.request("/api/v1/client/users/set-inviter", "POST", payload, cb)
end

-- Update Password
function M.post_users_update_password(payload, cb)
    rastar.request("/api/v1/client/users/update-password", "POST", payload, cb)
end

-- Update Profile
function M.post_users_update_profile(payload, cb)
    rastar.request("/api/v1/client/users/update-profile", "POST", payload, cb)
end

-- ===== video-assets =====
-- List My Progress
function M.get_video_assets_progress(payload, cb)
    rastar.request("/api/v1/client/video-assets/progress" .. qs(payload), "GET", nil, cb)
end

-- Save Progress
function M.post_video_assets_progress(payload, cb)
    rastar.request("/api/v1/client/video-assets/progress", "POST", payload, cb)
end

-- Get
function M.get_video_assets(videoAssetId, payload, cb)
    rastar.request("/api/v1/client/video-assets/" .. tostring(videoAssetId) .. qs(payload), "GET", nil, cb)
end

-- Get Progress
function M.get_video_assets_progress_by_video_asset_id(video_asset_id, payload, cb)
    rastar.request("/api/v1/client/video-assets/" .. tostring(video_asset_id) .. "/progress" .. qs(payload), "GET", nil, cb)
end

-- Set Progress
function M.post_video_assets_progress_by_video_asset_id(video_asset_id, payload, cb)
    rastar.request("/api/v1/client/video-assets/" .. tostring(video_asset_id) .. "/progress", "POST", payload, cb)
end

-- ===== video-content-categories =====
-- List Categories
function M.get_video_content_categories(payload, cb)
    rastar.request("/api/v1/client/video-content-categories" .. qs(payload), "GET", nil, cb)
end

-- ===== video-content-group-lists =====
-- Get By Key
function M.get_video_content_group_lists_by_key(key, payload, cb)
    rastar.request("/api/v1/client/video-content-group-lists/by-key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Get
function M.get_video_content_group_lists(id, payload, cb)
    rastar.request("/api/v1/client/video-content-group-lists/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== video-content-lists =====
-- Get By Key
function M.get_video_content_lists_by_key(key, payload, cb)
    rastar.request("/api/v1/client/video-content-lists/by-key/" .. tostring(key) .. qs(payload), "GET", nil, cb)
end

-- Get
function M.get_video_content_lists(id, payload, cb)
    rastar.request("/api/v1/client/video-content-lists/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- ===== video-content-years =====
-- List Years
function M.get_video_content_years(payload, cb)
    rastar.request("/api/v1/client/video-content-years" .. qs(payload), "GET", nil, cb)
end

-- ===== video-contents =====
-- List Items
function M.get_video_contents(payload, cb)
    rastar.request("/api/v1/client/video-contents" .. qs(payload), "GET", nil, cb)
end

-- List Bookmarks
function M.get_video_contents_bookmarks(payload, cb)
    rastar.request("/api/v1/client/video-contents/bookmarks" .. qs(payload), "GET", nil, cb)
end

-- Get Detail
function M.get_video_contents_by_id(id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(id) .. qs(payload), "GET", nil, cb)
end

-- Send Episode Reaction
function M.post_video_contents_episodes_reaction(video_content_id, episode_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/episodes/" .. tostring(episode_id) .. "/reaction", "POST", payload, cb)
end

-- Send Favorite
function M.post_video_contents_favorite(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/favorite", "POST", payload, cb)
end

-- Get Favorite Summary
function M.get_video_contents_favorite_summary(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/favorite/summary" .. qs(payload), "GET", nil, cb)
end

-- Register Rate
function M.post_video_contents_rate(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/rate", "POST", payload, cb)
end

-- Get Rate Total
function M.get_video_contents_rate_total(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/rate/total" .. qs(payload), "GET", nil, cb)
end

-- Send Reaction
function M.post_video_contents_reaction(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/reaction", "POST", payload, cb)
end

-- Get Reaction Summary
function M.get_video_contents_reaction_summary(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/reaction/summary" .. qs(payload), "GET", nil, cb)
end

-- Create Review
function M.post_video_contents_review(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/review", "POST", payload, cb)
end

-- List Reviews
function M.get_video_contents_reviews(video_content_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/reviews" .. qs(payload), "GET", nil, cb)
end

-- Send Comment Reaction
function M.post_video_contents_reviews_reaction(video_content_id, comment_id, payload, cb)
    rastar.request("/api/v1/client/video-contents/" .. tostring(video_content_id) .. "/reviews/" .. tostring(comment_id) .. "/reaction", "POST", payload, cb)
end

-- ===== viewer-user-profile-types =====
-- List Types
function M.get_viewer_user_profile_types(payload, cb)
    rastar.request("/api/v1/client/viewer-user-profile-types" .. qs(payload), "GET", nil, cb)
end

-- ===== viewer-user-profiles =====
-- List Mine
function M.get_viewer_user_profiles(payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles" .. qs(payload), "GET", nil, cb)
end

-- Create
function M.post_viewer_user_profiles(payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles", "POST", payload, cb)
end

-- Delete
function M.delete_viewer_user_profiles(id, payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles/" .. tostring(id) .. qs(payload), "DELETE", nil, cb)
end

-- Update
function M.patch_viewer_user_profiles(id, payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles/" .. tostring(id), "PATCH", payload, cb)
end

-- Clear History
function M.delete_viewer_user_profiles_search_history(profile_id, payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles/" .. tostring(profile_id) .. "/search-history" .. qs(payload), "DELETE", nil, cb)
end

-- List History
function M.get_viewer_user_profiles_search_history(profile_id, payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles/" .. tostring(profile_id) .. "/search-history" .. qs(payload), "GET", nil, cb)
end

-- Delete Entry
function M.delete_viewer_user_profiles_search_history_by_profile_id_entry_id(profile_id, entry_id, payload, cb)
    rastar.request("/api/v1/client/viewer-user-profiles/" .. tostring(profile_id) .. "/search-history/" .. tostring(entry_id) .. qs(payload), "DELETE", nil, cb)
end

-- ===== workflow-functions =====
-- List Public
function M.get_workflow_functions(payload, cb)
    rastar.request("/api/v1/client/workflow-functions" .. qs(payload), "GET", nil, cb)
end

-- Create Function
function M.post_workflow_functions(payload, cb)
    rastar.request("/api/v1/client/workflow-functions", "POST", payload, cb)
end

-- List Mine
function M.get_workflow_functions_mine(payload, cb)
    rastar.request("/api/v1/client/workflow-functions/mine" .. qs(payload), "GET", nil, cb)
end

-- Delete Function
function M.delete_workflow_functions(function_id, payload, cb)
    rastar.request("/api/v1/client/workflow-functions/" .. tostring(function_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Function
function M.get_workflow_functions_by_function_id(function_id, payload, cb)
    rastar.request("/api/v1/client/workflow-functions/" .. tostring(function_id) .. qs(payload), "GET", nil, cb)
end

-- Update Function
function M.patch_workflow_functions(function_id, payload, cb)
    rastar.request("/api/v1/client/workflow-functions/" .. tostring(function_id), "PATCH", payload, cb)
end

-- Report Function
function M.post_workflow_functions_report(function_id, payload, cb)
    rastar.request("/api/v1/client/workflow-functions/" .. tostring(function_id) .. "/report", "POST", payload, cb)
end

-- Run Function
function M.post_workflow_functions_run(function_id, payload, cb)
    rastar.request("/api/v1/client/workflow-functions/" .. tostring(function_id) .. "/run", "POST", payload, cb)
end

-- ===== workflows =====
-- List Workflows
function M.get_workflows(payload, cb)
    rastar.request("/api/v1/client/workflows" .. qs(payload), "GET", nil, cb)
end

-- Create Workflow
function M.post_workflows(payload, cb)
    rastar.request("/api/v1/client/workflows", "POST", payload, cb)
end

-- Get Node Types
function M.get_workflows_schemas_node_types(payload, cb)
    rastar.request("/api/v1/client/workflows/schemas/node-types" .. qs(payload), "GET", nil, cb)
end

-- Delete Workflow
function M.delete_workflows(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Workflow
function M.get_workflows_by_workflow_id(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. qs(payload), "GET", nil, cb)
end

-- Update Workflow
function M.put_workflows(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id), "PUT", payload, cb)
end

-- Attach Project
function M.post_workflows_attach_project(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/attach-project", "POST", payload, cb)
end

-- Clipboard Export
function M.post_workflows_clipboard_export(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/clipboard/export", "POST", payload, cb)
end

-- Clipboard Paste
function M.post_workflows_clipboard_paste(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/clipboard/paste", "POST", payload, cb)
end

-- List Collaborators
function M.get_workflows_collaborators(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/collaborators" .. qs(payload), "GET", nil, cb)
end

-- Upsert Collaborator
function M.put_workflows_collaborators(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/collaborators", "PUT", payload, cb)
end

-- Remove Collaborator
function M.delete_workflows_collaborators(workflow_id, target_user_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/collaborators/" .. tostring(target_user_id) .. qs(payload), "DELETE", nil, cb)
end

-- List Comments
function M.get_workflows_comments(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/comments" .. qs(payload), "GET", nil, cb)
end

-- Create Comment
function M.post_workflows_comments(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/comments", "POST", payload, cb)
end

-- Detach Project
function M.delete_workflows_detach_project(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/detach-project" .. qs(payload), "DELETE", nil, cb)
end

-- Delete Edges
function M.delete_workflows_edges(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/edges" .. qs(payload), "DELETE", nil, cb)
end

-- List Edges
function M.get_workflows_edges(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/edges" .. qs(payload), "GET", nil, cb)
end

-- Create Edge
function M.post_workflows_edges(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/edges", "POST", payload, cb)
end

-- Delete Edge
function M.delete_workflows_edges_by_workflow_id_edge_id(workflow_id, edge_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/edges/" .. tostring(edge_id) .. qs(payload), "DELETE", nil, cb)
end

-- Extract Workflow
function M.post_workflows_extract(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/extract", "POST", payload, cb)
end

-- Fork Workflow
function M.post_workflows_fork(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/fork", "POST", payload, cb)
end

-- List Forms
function M.get_workflows_forms(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/forms" .. qs(payload), "GET", nil, cb)
end

-- Create Form
function M.post_workflows_forms(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/forms", "POST", payload, cb)
end

-- Delete Form
function M.delete_workflows_forms(workflow_id, form_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/forms/" .. tostring(form_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Form
function M.get_workflows_forms_by_workflow_id_form_id(workflow_id, form_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/forms/" .. tostring(form_id) .. qs(payload), "GET", nil, cb)
end

-- Update Form
function M.patch_workflows_forms(workflow_id, form_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/forms/" .. tostring(form_id), "PATCH", payload, cb)
end

-- List Node Groups
function M.get_workflows_node_groups(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/node-groups" .. qs(payload), "GET", nil, cb)
end

-- Create Node Group
function M.post_workflows_node_groups(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/node-groups", "POST", payload, cb)
end

-- Delete Node Group
function M.delete_workflows_node_groups(workflow_id, group_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/node-groups/" .. tostring(group_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Node Group
function M.get_workflows_node_groups_by_workflow_id_group_id(workflow_id, group_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/node-groups/" .. tostring(group_id) .. qs(payload), "GET", nil, cb)
end

-- Update Node Group
function M.put_workflows_node_groups(workflow_id, group_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/node-groups/" .. tostring(group_id), "PUT", payload, cb)
end

-- List Nodes
function M.get_workflows_nodes(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes" .. qs(payload), "GET", nil, cb)
end

-- Create Node
function M.post_workflows_nodes(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes", "POST", payload, cb)
end

-- Create Node From Reusable
function M.post_workflows_nodes_from_reusable(workflow_id, reusable_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes/from-reusable/" .. tostring(reusable_id), "POST", payload, cb)
end

-- Delete Node
function M.delete_workflows_nodes(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes/" .. tostring(node_id) .. qs(payload), "DELETE", nil, cb)
end

-- Get Node
function M.get_workflows_nodes_by_workflow_id_node_id(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes/" .. tostring(node_id) .. qs(payload), "GET", nil, cb)
end

-- Update Node
function M.put_workflows_nodes(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes/" .. tostring(node_id), "PUT", payload, cb)
end

-- Update Node State
function M.patch_workflows_nodes_state(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/nodes/" .. tostring(node_id) .. "/state", "PATCH", payload, cb)
end

-- Publish As Node
function M.post_workflows_publish_as_node(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/publish-as-node", "POST", payload, cb)
end

-- List Runs
function M.get_workflows_runs(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/runs" .. qs(payload), "GET", nil, cb)
end

-- Run Full
function M.post_workflows_runs_full(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/runs/full", "POST", payload, cb)
end

-- Run Single Node
function M.post_workflows_runs_nodes(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/runs/nodes/" .. tostring(node_id), "POST", payload, cb)
end

-- Run Selected
function M.post_workflows_runs_selected(workflow_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/runs/selected", "POST", payload, cb)
end

-- Get Run
function M.get_workflows_runs_by_workflow_id_run_id(workflow_id, run_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/runs/" .. tostring(run_id) .. qs(payload), "GET", nil, cb)
end

-- Set Starter Node
function M.put_workflows_starter_node(workflow_id, node_id, payload, cb)
    rastar.request("/api/v1/client/workflows/" .. tostring(workflow_id) .. "/starter-node/" .. tostring(node_id), "PUT", payload, cb)
end

return M
