# Generates rastar/api.lua — named Lua wrappers for EVERY client endpoint of the
# Rastar (baziche/FastAPI) backend, straight from its OpenAPI spec.
#
# One-command update (fetches the latest spec, then regenerates):
#   python tools/gen_rastar_api.py --fetch
#
# Offline regeneration from the bundled spec:
#   python tools/gen_rastar_api.py
#
# Coverage: every /api/v1/client/* path+method becomes a function. Admin and
# partner endpoints are intentionally excluded (they need non-player tokens).
# Every generated function delegates to rastar.request() (rastar/rastar.lua), so
# auth, retries, cache-busting and proxy fallback all apply automatically.
import argparse, json, re, sys, urllib.request

ap = argparse.ArgumentParser()
ap.add_argument("--spec", default="tools/openapi.json")
ap.add_argument("--out", default="rastar/api.lua")
ap.add_argument("--fetch", action="store_true",
                help="download the latest spec from --url into --spec first")
ap.add_argument("--url", default="https://baziche-api-dev.rastar.ir/openapi.json")
args = ap.parse_args()

if args.fetch:
    print("fetching", args.url, "...")
    data = urllib.request.urlopen(args.url, timeout=90).read()
    json.loads(data)  # validate before overwriting
    open(args.spec, "wb").write(data)
    print("spec updated:", len(data), "bytes")

spec = json.load(open(args.spec, encoding="utf-8"))

PREFIX = "/api/v1/client/"

def lua_name(method, segs):
    parts = [method.lower()]
    for s in segs:
        if s.startswith("{"):
            continue
        parts.append(re.sub(r"[^0-9A-Za-z]+", "_", s).strip("_").lower())
    return "_".join(p for p in parts if p)

entries = []
seen = {}
for path in sorted(spec["paths"]):
    if not path.startswith(PREFIX):
        continue
    segs = path[len(PREFIX):].strip("/").split("/")
    for method, op in sorted(spec["paths"][path].items()):
        if method not in ("get", "post", "put", "patch", "delete"):
            continue
        params = [s[1:-1] for s in segs if s.startswith("{")]
        name = lua_name(method, segs)
        if name in seen:  # disambiguate collisions with param names / counter
            cand = name + ("_by_" + "_".join(re.sub(r"[^0-9A-Za-z]+", "_", p) for p in params) if params else "_2")
            while cand in seen:
                cand += "_"
            name = cand
        seen[name] = True
        summary = (op.get("summary") or "").strip()
        entries.append((name, method.upper(), path, params, summary,
                        segs[0] if segs else ""))

lines = []
lines.append("-- AUTO-GENERATED by tools/gen_rastar_api.py — do not edit by hand.")
lines.append("-- Covers EVERY /api/v1/client/* endpoint of the Rastar backend (see <api>/docs).")
lines.append("-- Update to the latest backend with ONE command:")
lines.append("--   python tools/gen_rastar_api.py --fetch")
lines.append("--")
lines.append("-- Every function: M.<name>(path_params..., payload, cb)")
lines.append("--   payload = body table (POST/PUT/PATCH) or query table (GET/DELETE); may be nil")
lines.append("--   cb(ok, data_or_error, raw_response)")
lines.append("local rastar = require \"rastar.rastar\"")
lines.append("")
lines.append("local M = {}")
lines.append("")
lines.append("local function qs(t)")
lines.append("    if not t then return \"\" end")
lines.append("    local parts = {}")
lines.append("    for k, v in pairs(t) do")
lines.append("        parts[#parts + 1] = tostring(k) .. \"=\" .. tostring(v):gsub(\"[^%w%-%._~]\", function(c)")
lines.append("            return string.format(\"%%%02X\", c:byte())")
lines.append("        end)")
lines.append("    end")
lines.append("    if #parts == 0 then return \"\" end")
lines.append("    return \"?\" .. table.concat(parts, \"&\")")
lines.append("end")
lines.append("")

cur_module = None
for name, method, path, params, summary, module in entries:
    if module != cur_module:
        cur_module = module
        lines.append("-- ===== %s =====" % module)
    arg_list = [re.sub(r"[^0-9A-Za-z_]", "_", p) for p in params] + ["payload", "cb"]
    if summary:
        lines.append("-- %s" % summary)
    lines.append("function M.%s(%s)" % (name, ", ".join(arg_list)))
    expr = '"%s"' % path
    for p in params:
        safe = re.sub(r"[^0-9A-Za-z_]", "_", p)
        expr = expr.replace("{%s}" % p, '" .. tostring(%s) .. "' % safe)
    expr = expr.replace(' .. ""', "")
    if method in ("GET", "DELETE"):
        lines.append("    rastar.request(%s .. qs(payload), \"%s\", nil, cb)" % (expr, method))
    else:
        lines.append("    rastar.request(%s, \"%s\", payload, cb)" % (expr, method))
    lines.append("end")
    lines.append("")

lines.append("return M")

open(args.out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
mods = len({e[5] for e in entries})
print("generated %s: %d functions across %d modules" % (args.out, len(entries), mods))
